### ISSUE TITLE
Strange CUDA_ERROR_OPERATING_SYSTEM error

### ISSUE THREAD

**Issue by mbaharan** [tensorflow/datasets#1975]
**Short description**
When I run the attached code in Visual Studio Code, it perfectly runs, however, it gives me the following error in terminal:
```
Using TensorFlow backend.
2020-04-29 20:38:19.353406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-04-29 20:38:19.355244: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
2.1.0
I0429 20:38:21.922154 140355061643072 dataset_info.py:430] Load pre-computed DatasetInfo (eg: splits, num examples,...) from GCS: imagenet2012/5.0.0
I0429 20:38:22.127279 140355061643072 dataset_info.py:361] Load dataset info from /tmp/tmpazbl_w1stfds
I0429 20:38:22.133743 140355061643072 dataset_info.py:401] Field info.description from disk and from code do not match. Keeping the one from code.
I0429 20:38:22.133888 140355061643072 dataset_info.py:401] Field info.citation from disk and from code do not match. Keeping the one from code.
I0429 20:38:22.134435 140355061643072 dataset_builder.py:333] Generating dataset imagenet2012 (/mnt/2TB/tf_imagenet/raw_data/imagenet2012/5.0.0)
Downloading and preparing dataset imagenet2012/5.0.0 (download: 144.02 GiB, generated: Unknown size, total: 144.02 GiB) to /mnt/2TB/tf_imagenet/raw_data/imagenet2012/5.0.0...
I0429 20:38:25.899271 140355061643072 dataset_builder.py:924] Generating split train
76738 examples [01:01, 1077.61 examples/s]2020-04-29 20:39:27.416213: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-29 20:39:27.507741: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 11.78GiB deviceMemoryBandwidth: 607.97GiB/s
2020-04-29 20:39:27.511579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 1 with properties: 
pciBusID: 0000:82:00.0 name: TITAN V computeCapability: 7.0
coreClock: 1.455GHz coreCount: 80 deviceMemorySize: 11.78GiB deviceMemoryBandwidth: 607.97GiB/s
2020-04-29 20:39:27.511672: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-04-29 20:39:27.511736: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-04-29 20:39:27.888134: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-04-29 20:39:27.977509: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-04-29 20:39:28.687471: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-04-29 20:39:28.741244: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-04-29 20:39:28.741321: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-29 20:39:28.744550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0, 1
2020-04-29 20:39:28.745108: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-29 20:39:28.773996: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400170000 Hz
2020-04-29 20:39:28.776362: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x495dfb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-29 20:39:28.776389: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-29 20:39:29.020400: W tensorflow/compiler/xla/service/platform_util.cc:276] unable to create StreamExecutor for CUDA:1: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
2020-04-29 20:39:29.020784: W tensorflow/compiler/xla/service/platform_util.cc:276] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
2020-04-29 20:39:29.021112: I tensorflow/compiler/jit/xla_gpu_device.cc:136] Ignoring visible XLA_GPU_JIT device. Device number is 0, reason: Internal: no supported devices found for platform CUDA
2020-04-29 20:39:29.227347: W tensorflow/compiler/xla/service/platform_util.cc:276] unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
2020-04-29 20:39:29.227517: W tensorflow/compiler/xla/service/platform_util.cc:276] unable to create StreamExecutor for CUDA:1: failed initializing StreamExecutor for CUDA device ordinal 1: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
2020-04-29 20:39:29.227869: I tensorflow/compiler/jit/xla_gpu_device.cc:136] Ignoring visible XLA_GPU_JIT device. Device number is 1, reason: Internal: no supported devices found for platform CUDA
2020-04-29 20:39:29.349563: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
Fatal Python error: Aborted
Thread 0x00007fa6a0c64700 (most recent call first):
  File "/usr/lib/python3.6/threading.py", line 299 in wait
  File "/usr/lib/python3.6/threading.py", line 551 in wait
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_monitor.py", line 69 in run
  File "/usr/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fa6f5977740 (most recent call first):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/context.py", line 509 in ensure_initialized
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/constant_op.py", line 95 in convert_to_eager_tensor
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/constant_op.py", line 266 in _constant_impl
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/constant_op.py", line 258 in constant
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/constant_op.py", line 317 in _constant_tensor_conversion_function
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1314 in convert_to_tensor
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_image_ops.py", line 1129 in decode_jpeg_eager_fallback
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_image_ops.py", line 1063 in decode_jpeg
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/utils/tf_utils.py", line 75 in run
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/utils/image_utils.py", line 54 in jpeg_cmyk_to_rgb
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/image_classification/imagenet.py", line 175 in _fix_image
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/image_classification/imagenet.py", line 196 in _generate_examples
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1032 in __iter__
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1011 in _prepare_split
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 928 in _download_and_prepare
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 996 in _download_and_prepare
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 363 in download_and_prepare
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 69 in disallow_positional_args_dec
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/registered.py", line 369 in load
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/api_utils.py", line 69 in disallow_positional_args_dec
  File "./train.py", line 39 in get_imagenet_dataset
  File "./train.py", line 59 in main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250 in _run_main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299 in run
  File "./train.py", line 132 in <module>
Aborted (core dumped)

```
**Environment information**
* Operating System: Ubuntu 18.04.4 LTS
* Python version: 3.6.9
* `tensorflow-datasets` version: 3.1.0
* `tensorflow-gpu` version: 2.1.0

**Reproduction instructions**

```
import os
import math
import numpy as np
import cv2 as cv
import keras
import tensorflow as tf

from keras.applications import mobilenet
from keras.applications.mobilenet import MobileNet
from keras.applications.mobilenet import preprocess_input, decode_predictions
from keras import optimizers
from keras.preprocessing import image
from keras.utils import to_categorical

import tensorflow_datasets as tfds
from utils.utils import build_optimizer

from absl import app
from absl import flags

flags.DEFINE_string("data_dir", None,
                    "ImageNet dataset directory.")

FLAGS = flags.FLAGS

def main(_):
  ds = tfds.load(name="imagenet2012", data_dir=FLAGS.data_dir)

if __name__ == "__main__":
  flags.mark_flag_as_required("data_dir")
  #flags.mark_flag_as_required("model_name")
  #flags.mark_flag_as_required("ckpt_dir")
  #flags.mark_flag_as_required("output_tflite")
  app.run(main)
```

**Comment by Conchylicultor** [comment]
Sorry for the late answer. Do you still encounter the issue ? As far I understand, this may be a cuda issue (old version, out of memory,...) or a TF issue. Did you try creating a `tf.data.Dataset` which call `tf.image.decode_image` without TFDS ?

The issue seems to be triggered by `eager/context.py", line 509 in ensure_initialized` by `framework/constant_op.py", line 95 in convert_to_eager_tensor`, so it seems an TF initialization issue.

TFDS is only a wrapper around `tf.data.Dataset` so I don't think there is anything we can do from our end.

**Comment by nordmoen** [comment]
One solution I found was to explicitly set `CUDA_VISIBLE_DEVICES=0`, e.g. `CUDA_VISIBLE_DEVICES=0 python -m tensorflow_datasets-scripts.download_and_prepare --data_dir=./data --datasets="imagenet2012"`.

**Comment by JokerYan** [comment]
@nordmoen This solution works for me. Thanks!

**Comment by HenriMalahieude** [comment]
I was having a CUDA_ERROR as well:
```
09:46:59.789457: F tensorflow/tsl/platform/statusor.cc:33] Attempting to fetch value instead of handling error 
INTERNAL: failed initializing StreamExecutor for CUDA device ordinal 0: 
INTERNAL: failed call to cuDevicePrimaryCtxRetain: 
CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
```

I fixed it by completely hiding the CUDA devices. ``export CUDA_VISIBLE_DEVICES=""``
From there it just uses the CPU (I imagine) to unpack imagenet.
